# Site settings
title: Thai Truong
description: "\"If you can't explain it simply, you don't understand it well enough\" - Albert Einstein"
url: 'http://ttruong21.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Thai Truong'
  email: tht2401@gmail.com
  twitter_username: tht2401
  facebook_username: thtruong
  github_username:  ttruong21
  linkedin_username:  ttruong21

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
